language: python
cache:
  directories:
      - $HOME/.cache/pip
python:
  - "3.5"
before_install:
  - sudo apt-get update
install:
  - pip install numpy scipy sympy cython==0.23.5 nose lxml matplotlib==1.5.0 networkx==1.11 pandas
  # PySB and dependencies
  - wget "http://www.csb.pitt.edu/Faculty/Faeder/wp-content/uploads/2017/04/BioNetGen-2.2.6-stable_Linux.tar.gz" -O bionetgen.tar.gz -nv
  - tar xzf bionetgen.tar.gz
  - export BNGPATH=`pwd`/BioNetGen-2.2.6-stable
  - pip install git+https://github.com/pysb/pysb.git
  # PyKQML
  - pip install git+https://github.com/bgyori/pykqml.git
  # INDRA
  - pip install git+https://github.com/sorgerlab/indra.git
  # Dependencies of Bioagents not covered by previous installs
  - sudo apt-get install graphviz
  - pip install pygraphviz ndex2
  - wget -nv "http://sorger.med.harvard.edu/data/bgyori/bioagents/drug_targets.db" -O bioagents/resources/drug_targets.db
  # Install utilities for running tests
  - pip install coverage
before_script:
  # Enable plotting on fake display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  # Run standard unit tests
  - cd $TRAVIS_BUILD_DIR
  - nosetests bioagents/tests -v --with-coverage --cover-inclusive --cover-package=bioagents
